global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "vllm-service"
    static_configs:
      - targets: ["localhost:8000"]

  - job_name: "dcgm"
    static_configs:
      - targets: ["localhost:9400"]

  - job_name: "node"
    static_configs:
      - targets: ["localhost:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["localhost:8080"]