global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "llm-service"
    static_configs:
      - targets: ["llm-service:8000"]
    metrics_path: /metrics

  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
